# Generated by Django 2.2.16 on 2020-11-01 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myd', '0002_auto_20201029_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='recorddetails',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
